"""initial schema — users, folders, files, file_versions, shares, link_shares, stars, activities

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-23 00:00:00

Hand-written rather than autogenerated: this environment has no live
Postgres instance to diff against (autogenerate needs a real DB
connection to compare current state vs. models). Every column, type,
default, FK, and constraint below is copied directly from app/models/,
so running `alembic upgrade head` against a fresh Postgres database
produces exactly the schema the ORM expects.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ---------------------------------------------------------------
    # Enum types (created explicitly so downgrade() can drop them —
    # Postgres ENUMs are independent objects, not tied to the column)
    # ---------------------------------------------------------------
    auth_provider_enum = postgresql.ENUM("email", "google", name="authprovider")
    share_role_enum = postgresql.ENUM("viewer", "editor", name="sharerole")
    activity_action_enum = postgresql.ENUM(
        "upload", "download", "rename", "move", "delete", "restore",
        "share", "unshare", "star", "unstar", "create_folder",
        name="activityaction",
    )
    activity_target_type_enum = postgresql.ENUM("file", "folder", name="activitytargettype")

    bind = op.get_bind()
    auth_provider_enum.create(bind, checkfirst=True)
    share_role_enum.create(bind, checkfirst=True)
    activity_action_enum.create(bind, checkfirst=True)
    activity_target_type_enum.create(bind, checkfirst=True)

    # create_type=False on every column use below — the four types were
    # just created explicitly above; without this, SQLAlchemy's DDL
    # compiler tries to CREATE TYPE a second time per column and fails.
    auth_provider_enum = postgresql.ENUM("email", "google", name="authprovider", create_type=False)
    share_role_enum = postgresql.ENUM("viewer", "editor", name="sharerole", create_type=False)
    activity_action_enum = postgresql.ENUM(
        "upload", "download", "rename", "move", "delete", "restore",
        "share", "unshare", "star", "unstar", "create_folder",
        name="activityaction", create_type=False,
    )
    activity_target_type_enum = postgresql.ENUM(
        "file", "folder", name="activitytargettype", create_type=False
    )

    # ---------------------------------------------------------------
    # users
    # ---------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=True),
        sa.Column("full_name", sa.String(255), nullable=True),
        sa.Column("avatar_url", sa.String(500), nullable=True),
        sa.Column("auth_provider", auth_provider_enum, nullable=False, server_default="email"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("storage_used_bytes", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("storage_quota_bytes", sa.BigInteger(), nullable=False, server_default=str(15 * 1024 * 1024 * 1024)),
    )
    op.create_index("ix_users_id", "users", ["id"])
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    # ---------------------------------------------------------------
    # folders (self-referential parent_id)
    # ---------------------------------------------------------------
    op.create_table(
        "folders",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("folders.id", ondelete="CASCADE"), nullable=True),
        sa.Column("is_starred", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_trashed", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("trashed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_folders_id", "folders", ["id"])
    op.create_index("ix_folders_owner_id", "folders", ["owner_id"])
    op.create_index("ix_folders_parent_id", "folders", ["parent_id"])

    # ---------------------------------------------------------------
    # files
    # ---------------------------------------------------------------
    op.create_table(
        "files",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("mime_type", sa.String(150), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("storage_key", sa.String(1000), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("folder_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("folders.id", ondelete="CASCADE"), nullable=True),
        sa.Column("is_starred", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_trashed", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("trashed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_files_id", "files", ["id"])
    op.create_index("ix_files_storage_key", "files", ["storage_key"], unique=True)
    op.create_index("ix_files_owner_id", "files", ["owner_id"])
    op.create_index("ix_files_folder_id", "files", ["folder_id"])

    # ---------------------------------------------------------------
    # file_versions
    # ---------------------------------------------------------------
    op.create_table(
        "file_versions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("files.id", ondelete="CASCADE"), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(1000), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("uploaded_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
    )
    op.create_index("ix_file_versions_id", "file_versions", ["id"])
    op.create_index("ix_file_versions_file_id", "file_versions", ["file_id"])
    op.create_index("ix_file_versions_storage_key", "file_versions", ["storage_key"], unique=True)

    # ---------------------------------------------------------------
    # shares (exactly one of file_id / folder_id — enforced by CheckConstraint)
    # ---------------------------------------------------------------
    op.create_table(
        "shares",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("files.id", ondelete="CASCADE"), nullable=True),
        sa.Column("folder_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("folders.id", ondelete="CASCADE"), nullable=True),
        sa.Column("shared_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("shared_with_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("role", share_role_enum, nullable=False, server_default="viewer"),
        sa.CheckConstraint(
            "(file_id IS NOT NULL AND folder_id IS NULL) OR (file_id IS NULL AND folder_id IS NOT NULL)",
            name="share_target_exactly_one",
        ),
    )
    op.create_index("ix_shares_id", "shares", ["id"])
    op.create_index("ix_shares_file_id", "shares", ["file_id"])
    op.create_index("ix_shares_folder_id", "shares", ["folder_id"])

    # ---------------------------------------------------------------
    # link_shares (public shareable links)
    # ---------------------------------------------------------------
    op.create_table(
        "link_shares",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("file_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("files.id", ondelete="CASCADE"), nullable=False),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("token", sa.String(64), nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_revoked", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index("ix_link_shares_id", "link_shares", ["id"])
    op.create_index("ix_link_shares_file_id", "link_shares", ["file_id"])
    op.create_index("ix_link_shares_token", "link_shares", ["token"], unique=True)

    # ---------------------------------------------------------------
    # stars (exactly one of file_id / folder_id — enforced by CheckConstraint)
    # ---------------------------------------------------------------
    op.create_table(
        "stars",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("file_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("files.id", ondelete="CASCADE"), nullable=True),
        sa.Column("folder_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("folders.id", ondelete="CASCADE"), nullable=True),
        sa.CheckConstraint(
            "(file_id IS NOT NULL AND folder_id IS NULL) OR (file_id IS NULL AND folder_id IS NOT NULL)",
            name="star_target_exactly_one",
        ),
        sa.UniqueConstraint("user_id", "file_id", "folder_id", name="uq_star_per_user_target"),
    )
    op.create_index("ix_stars_id", "stars", ["id"])
    op.create_index("ix_stars_user_id", "stars", ["user_id"])

    # ---------------------------------------------------------------
    # activities (audit log)
    # ---------------------------------------------------------------
    op.create_table(
        "activities",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("action", activity_action_enum, nullable=False),
        sa.Column("target_type", activity_target_type_enum, nullable=False),
        sa.Column("target_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("target_name_snapshot", sa.String(255), nullable=True),
    )
    op.create_index("ix_activities_id", "activities", ["id"])
    op.create_index("ix_activities_user_id", "activities", ["user_id"])
    op.create_index("ix_activities_target_id", "activities", ["target_id"])


def downgrade() -> None:
    # Reverse order — children before parents, to respect FKs.
    op.drop_table("activities")
    op.drop_table("stars")
    op.drop_table("link_shares")
    op.drop_table("shares")
    op.drop_table("file_versions")
    op.drop_table("files")
    op.drop_table("folders")
    op.drop_table("users")

    bind = op.get_bind()
    postgresql.ENUM(name="activitytargettype").drop(bind, checkfirst=True)
    postgresql.ENUM(name="activityaction").drop(bind, checkfirst=True)
    postgresql.ENUM(name="sharerole").drop(bind, checkfirst=True)
    postgresql.ENUM(name="authprovider").drop(bind, checkfirst=True)